### ISSUE TITLE
Two of the 3 examples cited are not in repo

### ISSUE THREAD

**Issue by dspdon** [Seeed-Studio/Seeed_AMG8833#3]
The README indicates 3 demos, but only the first (basic_demo) is present in the repo:
exambles/basic_demo.ino - PRESENT
exambles/TFT_screen_demo.ino - MISSING
exambles/thermal_cam_interpolate/thermal_cam_interpolate.ino - MISSING

**Comment by dspdon** [comment]
The code for the TFT-based demo is cited in the main page on Wio Terminal wiki, which I presume was the intent of the TFT-based demo:
https://wiki.seeedstudio.com/Wio-Terminal-Thermal-Camera/

**Comment by Cincinnatu** [comment]
Hello! As this is just the library file of AMG8833, the remaining two examples are in the library for other devices they use.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
